name: ExplosionProtector
version: '1.0'
main: org.SlidrusForeal.explosionProtector.ExplosionProtector
api-version: '1.21'
depend:
  - CoreProtect

commands:
  ep:
    description: ExplosionProtector commands (status, info, language)
    usage: /ep <status|info|language>
    aliases:
      - explosionprot
