name: ExplosionProtector
version: '1.0'
main: org.SlidrusForeal.explosionProtector.ExplosionProtector
api-version: '1.21'
authors: [ "SlidrusForeal" ]
depend: [CoreProtect]
description: Protects your server from explosions using  coreprotect database
commands:
  explosionprotector:
    description: Manage the ExplosionProtector plugin.
    usage: /explosionprotector <enable|disable|stats|cache>